language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7
  - hhvm

before_script:
    - travis_retry curl -s http://getcomposer.org/installer | php
    - travis_retry php composer.phar install
    - mkdir -p build/logs

script:
    - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_script:
  - php vendor/bin/coveralls

matrix:
  allow_failures:
    - php: 7
    - php: hhvm

notifications:
  hipchat:
    rooms:
      secure: "PZH/uc98bkKmV1vn0zP8rhxV1NZ0orTlapTZ5gYMqCiagYrkCOjcPWFOnJmZNQ7II9ORI5HsWNrXWDHWQVYd95sSnPEnFw801OZMU4zxrvsyXerrw5j3cKR8MrRFnYxOxvSsCGGV5iiuifqlLIyg6GkJI6q64nry5aj3f4nJRw8="
