language: php

php:
  - '7.2'
  - '7.3'
  - '7.4'

before_script:
    - composer self-update
    - composer install
    - mkdir -p build/logs

script:
    - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_script:
  - php vendor/bin/php-coveralls

notifications:
  hipchat:
    rooms:
      secure: "PZH/uc98bkKmV1vn0zP8rhxV1NZ0orTlapTZ5gYMqCiagYrkCOjcPWFOnJmZNQ7II9ORI5HsWNrXWDHWQVYd95sSnPEnFw801OZMU4zxrvsyXerrw5j3cKR8MrRFnYxOxvSsCGGV5iiuifqlLIyg6GkJI6q64nry5aj3f4nJRw8="
