language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_script:
    - travis_retry curl -s http://getcomposer.org/installer | php
    - travis_retry php composer.phar install --dev

script:
    - vendor/bin/phpunit

matrix:
  allow_failures:
    - php: hhvm